// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Data;

#nullable disable

namespace PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20250123161712_DemoDb Migration")]
    partial class DemoDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Accessed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alamat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nama");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("accessed");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Accessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alamat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nama");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("accessor");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alamat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nama");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessedId")
                        .HasColumnType("int")
                        .HasColumnName("id assessi");

                    b.Property<int>("AccessorId")
                        .HasColumnType("int")
                        .HasColumnName("id assessor");

                    b.Property<string>("AssessmentAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jawaban assessment");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("id pertanyaan");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int")
                        .HasColumnName("id soal");

                    b.HasKey("Id");

                    b.ToTable("jawaban_peserta_assessi");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.AnswerVerified", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessedId")
                        .HasColumnType("int")
                        .HasColumnName("id assessi");

                    b.Property<int>("AccessorId")
                        .HasColumnType("int")
                        .HasColumnName("id assessor");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jawaban");

                    b.Property<int>("AssessmentSessionId")
                        .HasColumnType("int")
                        .HasColumnName("id sesi assessment");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pertanyaan");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int")
                        .HasColumnName("id soal");

                    b.Property<string>("Rekomendasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rekomendasi");

                    b.Property<string>("Tanggapan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tanggapan");

                    b.HasKey("Id");

                    b.ToTable("jawaban_peserta_assessi_terverifikasi");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.AssessmentSession", b =>
                {
                    b.Property<int>("AssessmentSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id sesi assessment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentSessionId"));

                    b.HasKey("AssessmentSessionId");

                    b.ToTable("sesi_assessment");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int")
                        .HasColumnName("id soal");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.ToTable("pertanyaan");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessorId")
                        .HasColumnType("int")
                        .HasColumnName("id accessor");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Deskripsi");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul");

                    b.HasKey("Id");

                    b.ToTable("soal");
                });

            modelBuilder.Entity("PBL_Semester5_Aplikasi_Sertifikasi_v2.Api.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessedId")
                        .HasColumnType("int")
                        .HasColumnName("id Assessi");

                    b.Property<int>("AccessorID")
                        .HasColumnType("int")
                        .HasColumnName("id Assessor");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int")
                        .HasColumnName("id Soal");

                    b.HasKey("Id");

                    b.ToTable("jadwal");
                });
#pragma warning restore 612, 618
        }
    }
}
